channels:
  - conda-forge
dependencies:
  - python >=3.9,<3.10
  - pip >=22.2.2
  - numpy >=1.21.2,<1.23.3
  - netCDF4 >=1.5.5,<1.6.1
  - gdal >=3.3.3,<3.5.1
  - pandas >=1.3.2,<1.5.0
  - pyramids >=0.2.2
  - ecmwf-api-client >=1.6.3
  - earthengine-api >=0.1.324
  - pip:
      - loguru >=0.6.0
      - pytest >=7.1.3
      - pytest-cov >=3.0.0
