channels:
  - conda-forge
dependencies:
  - python >=3.9,<3.11
  - numpy ==1.24.1
  - pip >=22.3.1
  - gdal >=3.5.3
  - netCDF4 >=1.6.1
  - pandas >=1.4.4
  - ecmwf-api-client >=1.6.3
  - earthengine-api >=0.1.324
  - boto3 >=1.26.50
  - joblib >=1.2.0
  - pyramids >=0.2.12
  - loguru >=0.6.0
  - PyYAML >=6.0
  - pathlib >=1.0.1
  - pytest >=7.2.0
  - pytest-cov ==4.0.0
  - requests >=2.28.1
