channels:
  - conda-forge
dependencies:
  - numpy >=2.0.0
  - pip >=24.0.0
  - gdal ==3.9.0
  - pandas >=2.1.0
  - netCDF4 ==1.6.5
  - ecmwf-api-client >=1.6.3
  - earthengine-api >=0.1.414
  - boto3 >=1.34.153
  - joblib >=1.4.2
  - pyramids >=0.7.0
  - serapeum_utils >=0.2.0
  - loguru >=0.7.2
  - PyYAML >=6.0.1
  - pytest >=8.2.2
  - pytest-cov >=5.0.0
  - requests >=2.28.1
  - nbval >=0.11.0
