channels:
  - conda-forge
dependencies:
  - numpy >=2.1.3
  - pip >=24.3.1
  - netCDF4 >=1.6.1
  - pandas >=2.2.3
  - ecmwf-api-client >=1.6.3
  - earthengine-api >=0.1.324
  - boto3 >=1.26.50
  - joblib >=1.2.0
  - pyramids >=0.7.1
  - serapeum_utils >=0.1.1
  - loguru >=0.7.2
  - PyYAML >=6.0.2
  - pathlib >=1.0.1
  - pytest >=8.2.2
  - pytest-cov >=5.0.0
  - requests >=2.28.1
