channels:
  - conda-forge
dependencies:
  - pandas
  - numpy==1.20.*
  - numpydoc==1.1.0
  - typing-extensions==3.10.*
  - gdal==3.10.0
  - pip:
    - pydata_sphinx_theme>=0.15.2
    - sphinxcontrib-napoleon
    - nbsphinx
    - ../.
